experiment_name: "dia_plus"
task_type: "text_classification"
output_type: "per_sequence"
multilabel: true
metric: "binary_classification_metrics"
output_dir: "/models/cop-dia-plus/"
log_dir: "/models/cop-dia-plus/logs"
data:
  data_dir: "/data/mimic-iii-processed"
  train_filename: "DIA_PLUS_adm_train.csv"
  dev_filename: "DIA_PLUS_adm_val.csv"
  test_filename: "DIA_PLUS_adm_test.csv"
  label_list: "ALL_DIAGNOSES_PLUS_CODES.txt"
  parsing:
    label_column: "labels"
    delimiter: ","
    quote_char: "\""
