apiVersion: batch/v1
kind: Job
metadata:
  name: pro-3-core-d
  labels:
    app: pro-3-core-d
spec:
  template:
    metadata:
      labels:
        app: pro-3-core-d
    spec:
      containers:
        - name: pro-3-core-d
          image: registry.datexis.com/tsteffek/clinical-outcome-prediction:0.0.18
          command: [
            "python", "/experiments/doc_classification.py",
            "--task_config", "/data/configs/iii/train/config_pro_3.yaml",
            "--model_name_or_path", "bvanaken/CORe-clinical-outcome-biobert-v1",
            "--cache_dir", "/models/cache",
#            "--balance_classes", "False",
#            "--embeds_dropout", "0.260609",
#            "--grad_acc", "20",
#            "--lr", "6.17666e-05",
#            "--warmup_steps", "1894.28",
            "--run_name", "core-d"
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
          resources:
            requests:
              cpu: "2"
              memory: 10Gi
            limits:
              nvidia.com/gpu: "1"
              memory: 20Gi
          volumeMounts:
            - name: pe-models
              mountPath: /models
            - name: mimic-iii
              mountPath: /data
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: mimic-iii
          persistentVolumeClaim:
            claimName: mimic-iii
        - name: pe-models
          persistentVolumeClaim:
            claimName: pe-models
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
