apiVersion: batch/v1
kind: Job
metadata:
  name: proto-eval
  labels:
    app: proto-eval
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: proto-eval
    spec:
      containers:
        - name: proto-eval
          image: registry.datexis.com/tsteffek/protopatient:0.0.19
          command: [
            "python", "testing.py",
            "--model_type", "PROTO",
            "--train_file", "/data/mimic-iv-processed/empty.csv",
            "--val_file", "/data/mimic-iv-processed/empty.csv",
            "--test_file", "/data/mimic-iv-processed/dia.csv",
            "--num_warmup_steps", "5000",
            "--num_training_steps", "5000",
            "--lr_features", "0.000005",
            "--lr_prototypes", "0.001",
            "--gpus", "4",
            "--lr_others", "0.001",
            "--use_attention", "True",
            "--reduce_hidden_size", "256",
            "--all_labels_path", "/data/mimic-iv-processed/ALL_3_DIGIT_DIA_CODES.txt",
            "--save_dir", "/models/proto/",
            "--resume_from_checkpoint", "/models/final/proto/checkpoints/ckpt-epoch=297.ckpt",
            "--do_train", "False",
            "--label_column", "labels",
            "--id_column", "hadm_id"
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
          resources:
            requests:
              cpu: "2"
              memory: 30Gi
            limits:
              nvidia.com/gpu: "1"
              memory: 100Gi
          volumeMounts:
            - name: pe-models
              mountPath: /models
            - name: mimic-iii
              mountPath: /data
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: mimic-iii
          persistentVolumeClaim:
            claimName: mimic-iii
        - name: pe-models
          persistentVolumeClaim:
            claimName: pe-models
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never


#	    III	    iii_test  IV        HOSP	ICU	    IV_ICU \ Sep	Matching
#Dia 	83.05%	81.06%	  80.55%	79.38%	83.14%	79.32%	        90.90%
#Dia+	83.21%	81.20%	  79.27%	78.26%	81.69%	78.48%	        88.44%
#Dia+2	82.56%	79.98%	  78.83%	77.96%	80.91%	78.22%	        87.28%
#Pro	    87.68%	88.75%	  86.47%	85.38%	88.40%	87.63%	        91.24%
#Pro+	88.08%	88.66%	  86.62%	85.25%	88.90%	87.19%	        93.04%
#LoS 	72.10%	71.69%	  61.27%	59.57%	71.38%	60.99%	        74.80%
#LoS_IV	-	    62.68%	  59.85%	59.57%	60.99%	59.10%	        63.88%
#MP	    83.10%	82.84%	  86.09%	84.83%	84.29%	82.81%	        86.20%
#
#
#        &  III    &  IV     &  HOSP   &  ICU    &  IV_ICU \ Sep \\\hline
#Dia     &  83.05  &  80.55  &  79.38  &  83.14  &  79.32        \\
#Dia+    &  83.21  &  79.27  &  78.26  &  81.69  &  78.48        \\
#Dia+2   &  82.56  &  78.83  &  77.96  &  80.91  &  78.22        \\
#Pro     &  87.68  &  86.47  &  85.38  &  88.40  &  87.63        \\
#Pro+    &  88.08  &  86.62  &  85.25  &  88.90  &  87.19        \\
#LoS     &  72.10  &  61.27  &  59.57  &  71.38  &  60.99        \\
#MP      &  83.10  &  86.09  &  84.83  &  84.29  &  82.81        \\
#
#
#
#                       &  $III$     & \SetCell[c=2]{c}    $IV_{ALL}$	   & &	\SetCell[c=2]{c} $IV_{HOSP}$   & &	\SetCell[c=2]{c} $IV_{ICU}$	& &	\SetCell[c=2]{c} $IV_{ICU\setminus III}$ &  \\\hline
#Diagnoses              &  83.05   &  	-2.50             &  (80.55)  &  -3.67             & (79.38)  &\underline{+0.09} &   (83.14)  &  -3.73    &  (79.32) \\
#Diagnoses ICD+         &  83.21   &  	-3.94             &  (79.27)  &  -4.95             & (78.26)  &     -1.51        &   (81.69)  &  -4.73    &  (78.48) \\
#Procedures             &  87.68   &  	-1.21             &  (86.47)  &  -2.30             & (85.38)  &\underline{+0.72} &   (88.40)  &  -0.05    &  (87.63) \\
#Procedures ICD+        &  88.08   &  	-1.46             &  (86.62)  &  -2.83             & (85.25)  &\underline{+0.82} &   (88.90)  &  -0.89    &  (87.19) \\
#Length-of-Stay         &  72.10   &  	\textbf{-10.83}   &  (61.27)  &  \textbf{-12.53}   & (59.57)  &     -0.72        &   (71.38)  &  -11.12   &  (60.99) \\
#In-Hospital Mortality  &  83.10   &  	+2.99             &  (86.09)  &  \underline{+1.73} & (84.83)  &\underline{+1.19} &   (84.29)  &  -0.29    &  (82.81) \\
#


