apiVersion: batch/v1
kind: Job
metadata:
  name: dia-3-ts
  labels:
    app: dia-3-ts
spec:
  template:
    metadata:
      labels:
        app: dia-3-ts
    spec:
      containers:
        - name: dia-3-ts
          image: registry.datexis.com/tsteffek/clinical-outcome-prediction:0.0.18
          command: [
            "python", "/experiments/doc_classification.py",
            "--task_config", "/data/configs/iii/train/config_dia_3.yaml",
            "--model_name_or_path", "dmis-lab/biobert-v1.1",
            "--cache_dir", "/models/cache",
            "--balance_classes", "False",
            "--embeds_dropout", "0.185546",
            "--grad_acc", "1",
            "--lr", "4.59433e-05",
            "--warmup_steps", "3589.71"
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
          resources:
            requests:
              cpu: "2"
            limits:
              nvidia.com/gpu: "1"
              memory: 30Gi
          volumeMounts:
            - name: pe-models
              mountPath: /models
            - name: mimic-iii
              mountPath: /data
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: mimic-iii
          persistentVolumeClaim:
            claimName: mimic-iii
        - name: pe-models
          persistentVolumeClaim:
            claimName: pe-models
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
