apiVersion: batch/v1
kind: Job
metadata:
  name: {{ experiment }}
  labels:
    app: {{ experiment }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ experiment }}
    spec:
      containers:
        - name: {{ experiment }}
          image: registry.datexis.com/tsteffek/clinical-outcome-prediction:0.0.19
          command: [
            "python", "/experiments/doc_classification.py",
            "--task_config", {{ task_config }},
            "--model_name_or_path", {{ model_name }},
            "--cache_dir", "None",
            "--do_train", "False",
            "--print_preds", "True",
            "--run_name", "eval"
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
          resources:
            requests:
              cpu: "1"
              memory: 20Gi
            limits:
              nvidia.com/gpu: "1"
              memory: 100Gi
          volumeMounts:
            - name: pe-models
              mountPath: /models
            - name: mimic-iii
              mountPath: /data
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: mimic-iii
          persistentVolumeClaim:
            claimName: mimic-iii
        - name: pe-models
          persistentVolumeClaim:
            claimName: pe-models
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
