apiVersion: batch/v1
kind: Job
metadata:
  name: los-hpo
  labels:
    app: los-hpo
spec:
  template:
    metadata:
      labels:
        app: los-hpo
    spec:
      containers:
        - name: los-hpo
          image: registry.datexis.com/tsteffek/clinical-outcome-prediction:0.0.18
          command: [
            "python", "/experiments/hpo_doc_classification.py",
            "--task_config", "/data/configs/iii/train/config_los.yaml",
            "--model_name", "dmis-lab/biobert-v1.1",
            "--hpo_samples", "20",
            "--hpo_gpus", "1",
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
          resources:
            requests:
              cpu: "4"
            limits:
              nvidia.com/gpu: "2"
              memory: 30Gi
          volumeMounts:
            - name: pe-models
              mountPath: /models
            - name: mimic-iii
              mountPath: /data
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: mimic-iii
          persistentVolumeClaim:
            claimName: mimic-iii
        - name: pe-models
          persistentVolumeClaim:
            claimName: pe-models
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
