apiVersion: batch/v1
kind: Job
metadata:
  name: pro-3-hpo
  labels:
    app: pro-3-hpo
spec:
  template:
    metadata:
      labels:
        app: pro-3-hpo
    spec:
      containers:
        - name: pro-3-hpo
          image: registry.datexis.com/tsteffek/clinical-outcome-prediction:0.0.18
          command: [
            "python", "/experiments/hpo_doc_classification.py",
            "--task_config", "/data/configs/iii/train/config_pro_3.yaml",
            "--model_name", "bvanaken/CORe-clinical-outcome-biobert-v1",
            "--hpo_samples", "20",
            "--hpo_gpus", "1",
            "--lr_end", "1e-4",
            "--run_name", "core-hpo",
            "--seed", "42"
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
          resources:
            requests:
              cpu: "1"
              memory: 25Gi
            limits:
              nvidia.com/gpu: "1"
              memory: 50Gi
          volumeMounts:
            - name: pe-models
              mountPath: /models
            - name: mimic-iii
              mountPath: /data
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: mimic-iii
          persistentVolumeClaim:
            claimName: mimic-iii
        - name: pe-models
          persistentVolumeClaim:
            claimName: pe-models
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
